name: Pipeline Main da produção

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Baixar Artefato
        uses: actions/download-artifact@v4
        with:
          name: codigo-buildado

      - name: Extrair Artefato
        run: unzip -o pipeline-demo.zip

      - name: Simular deploy
        run: echo "Deploy realizado com sucesso"