name: Pipeline Main da produção

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Simular deploy
        run: echo "Deploy realizado com sucesso"